version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/go-git/go-git/v5
    versions:
    - 5.3.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
    - 1.1.3
