kind: pipeline
type: docker
name: bot-builder

trigger:
  event:
    - tag

steps:
  - name: bot-builder
    image: plugins/docker
    settings:
      repo: raf924/relay-builder
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token
